### ISSUE TITLE
missing dependency with latest 8.4.0 image?

### ISSUE THREAD

**Issue by chrishavlin** [gnu-octave/docker#20]
Hi there, 

I've got a github action that pulls in the latest docker image that started failing with the following error

```
/usr/bin/octave-cli-8.4.0: error while loading shared libraries: libcholmod.so.5: cannot open shared object file: No such file or directory
```

Here's a copy of the action for reference

```
name: Octave Build

on:
  pull_request:
    paths:
    - "**.m"
    - ".github/workflows/build-test-octave.yaml"

jobs:
  test-on-octave:
    name: Octave build
    runs-on: ubuntu-latest
    container:
      image: gnuoctave/octave
    steps:
    - uses: actions/checkout@v4
    - name: Check octave installation
      run: octave --eval "disp(version)"
    - name: Run tests
      run: octave --eval "run_all_tests"
```

The error is coming from the `octave --eval "disp(version)"` step. Pinning the image to `gnuoctave/octave:8.3.0` solves the error.

Any ideas? Totally possible I should be doing something differently -- should I be installing the docker image more manually maybe? As I understand it, the current setup in the above action relies on github to pull the image from DockerHub, but I don't use docker much and maybe this is user error on my part....
